name: Guatemala_env
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - r-base=4.3.3
  - r-rsconnect
  - r-janitor
  - r-tidyverse
  - r-remotes
  - r-usethis=2.2.3
  - r-REDCapR=1.1.0
  - r-ggplot2=3.5.1
  - r-lubridate=1.9.4
  - r-purrr=1.0.2
  - r-ggrepel=0.9.5
  - r-dplyr=1.1.4
  - r-shiny
  - r-bslib=0.7.0
  - r-shinythemes=1.2.0
  - r-reactable=0.4.4
  - r-tidyr=1.3.1
  - r-digest=0.6.36
  - r-patchwork=1.2.0
  - r-DT=0.33
  - r-stringr=1.5.1
